name: qhack2022-hackeinberg-project
channels:
  - conda-forge
dependencies:
  - python==3.7.12 
  - numpy==1.20.3
  - PennyLane==0.21.0
  - matplotlib==3.5.1
  - jupyter

# To create this environment:
## conda env create -n <env_name> environment.yml 

# To manually install the above packages with Conda:
## $ conda update -n base -c defaults conda
## $ conda install python==3.7.12 
## $ conda install numpy==1.20.3 
## $ conda install -c conda-forge PennyLane==0.21.0
## $ conda install matplotlib==3.5.1
## $ conda install jupyter

# Future updates
## $ conda env update -n <env_name_exist> --file environment.yml --prune && conda activate <env_name_exist> && python3 -m pip install --no-deps -e -v .

# To export your changes to a new conda env. (suggested for sharing between users):
## $ conda env export --from-history -n <env_name_exist> > environment.yml

# CLI - command-line interface
## To show env. info: $ conda info
## To show installed packages: $ conda list
## To list a package info: $ conda list <package_name>
## To remove the env.: $ conda remove --name <env_name_exists> --all

# Other packages that must be installed via pip: 
## $ python3 -m pip install -U qamuy-client --extra-index-url https://download.qamuy.qunasys.com/simple/
## $ python3 -m pip install pennylane-qchem==0.21.0
## $ python3 -m pip install pyscf --user
## $ python3 -m pip install openfermionpyscf==0.5
